language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test
    - stage: notify
      script: scripts/deploy-notify.sh

    - stage: deploy
      name: Deploy Officer
      script: scripts/deploy.js officer

    - stage: deploy
      name: Deploy Evaluation Engineering
      script: scripts/deploy.js evaluationengineering

    - stage: deploy
      name: Deploy Utility Products
      script: scripts/deploy.js utilityproducts

    - stage: deploy
      name: Deploy Dental Economics
      script: scripts/deploy.js dentaleconomics

    - stage: deploy
      name: Deploy BioOptics World
      script: scripts/deploy.js bioopticsworld

    - stage: deploy
      name: Deploy Broadband Technology Report
      script: scripts/deploy.js broadbandtechreport

    - stage: deploy
      name: Deploy Cabling Installation & Maintenance
      script: scripts/deploy.js cablinginstall

    - stage: deploy
      name: Deploy DentistryIQ
      script: scripts/deploy.js dentistryiq

    - stage: deploy
      name: Deploy Intelligent Aerospace
      script: scripts/deploy.js intelligent-aerospace

    - stage: deploy
      name: Deploy Industrial Laser Solutions
      script: scripts/deploy.js industrial-lasers

    - stage: deploy
      name: Deploy LEDs Magazine
      script: scripts/deploy.js ledsmagazine

    - stage: deploy
      name: Deploy Laser Focus World
      script: scripts/deploy.js laserfocusworld

    - stage: deploy
      name: Lightwave
      script: scripts/deploy.js lightwaveonline

    - stage: deploy
      name: Military & Aerospace Electronics
      script: scripts/deploy.js militaryaerospace

    - stage: deploy
      name: Offshore Magazine
      script: scripts/deploy.js offshore-mag
