version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  volumes:
    - .:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]


services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  cli:
    <<: *node
    working_dir: /root/sites
    entrypoint: ["/root/node_modules/.bin/basecms-website"]
    environment:
      <<: *env

  lint:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    command: ["run", "lint"]
    environment:
      <<: *env

  evaluation-engineering:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/evaluation-engineering
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12151
      LIVERELOAD_PORT: 35151
      GRAPHQL_URI: https://graphql.base-cms.io/ebm/ee
    ports:
      - "12151:80"
      - "35151:35151"

  officer:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/officer
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12152
      LIVERELOAD_PORT: 35152
      GRAPHQL_URI: https://graphql.base-cms.io/ebm/ofcr
    ports:
      - "12152:80"
      - "35152:35152"

volumes:
  yarn-cache: {}
