version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.base-cms.io/graphql}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: developer@endeavorb2b.com
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-aerilon: &env-aerilon
  GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
  OEMBED_URI: ${OEMBED_URI-https://aerilon.oembed.base-cms.io}
  RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
  SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}

x-env-caprica: &env-caprica
  GRAPHQL_URI: ${GRAPHQL_URI-https://caprica.graphql.base-cms.io}
  OEMBED_URI: ${OEMBED_URI-https://caprica.oembed.base-cms.io}
  RSS_URI: ${RSS_URI-https://caprica.rss.base-cms.io}
  SITEMAPS_URI: ${SITEMAPS_URI-https://caprica.sitemaps.base-cms.io}

x-env-picon: &env-picon
  GRAPHQL_URI: ${GRAPHQL_URI-https://picon.graphql.base-cms.io}
  OEMBED_URI: ${OEMBED_URI-https://picon.oembed.base-cms.io}
  RSS_URI: ${RSS_URI-https://picon.rss.base-cms.io}
  SITEMAPS_URI: ${SITEMAPS_URI-https://picon.sitemaps.base-cms.io}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  cli:
    <<: *node
    working_dir: /root/sites
    entrypoint: ["/root/node_modules/.bin/basecms-website"]
    environment:
      <<: *env

  lint:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    command: ["run", "lint"]
    environment:
      <<: *env

  ogj:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/ogj
    environment:
      <<: *env
      <<: *env-aerilon
      PORT: 80
      EXPOSED_PORT: 12166
      LIVERELOAD_PORT: 35166
      TENANT_KEY: ebm_ogj
    ports:
      - "12166:80"
      - "35166:35166"

  waterworld:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/waterworld
    environment:
      <<: *env
      <<: *env-aerilon
      PORT: 80
      EXPOSED_PORT: 12171
      LIVERELOAD_PORT: 35171
      TENANT_KEY: ebm_ww
    ports:
      - "12171:80"
      - "35171:35171"

  mundopmmi:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/mundopmmi
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 12189
      LIVERELOAD_PORT: 35189
      TENANT_KEY: pmmi_mundo
    ports:
      - "12189:80"
      - "35189:35189"

  bizbash:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/bizbash
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 12190
      LIVERELOAD_PORT: 35190
      TENANT_KEY: bizbash_bzb
    ports:
      - "12190:80"
      - "35190:35190"
