version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - .:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  cli:
    <<: *node
    working_dir: /root/sites
    entrypoint: ["/root/node_modules/.bin/basecms-website"]
    environment:
      <<: *env

  lint:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    command: ["run", "lint"]
    environment:
      <<: *env

  evaluationengineering:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/evaluationengineering
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12151
      LIVERELOAD_PORT: 35151
      SITEMAPS_URI: ${SITEMAPS_URI-https://picon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://picon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://picon.graphql.base-cms.io}
      TENANT_KEY: ebm_ee
    ports:
      - "12151:80"
      - "35151:35151"

  officer:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/officer
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12152
      LIVERELOAD_PORT: 35152
      SITEMAPS_URI: ${SITEMAPS_URI-https://picon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://picon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://picon.graphql.base-cms.io}
      TENANT_KEY: cygnus_ofcr
    ports:
      - "12152:80"
      - "35152:35152"

  utilityproducts:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/utilityproducts
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12153
      LIVERELOAD_PORT: 35153
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_up
    ports:
      - "12153:80"
      - "35153:35153"

  dentaleconomics:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/dentaleconomics
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12154
      LIVERELOAD_PORT: 35154
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_de
    ports:
      - "12154:80"
      - "35154:35154"

  bioopticsworld:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/bioopticsworld
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12155
      LIVERELOAD_PORT: 35155
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_bow
    ports:
      - "12155:80"
      - "35155:35155"

  broadbandtechreport:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/broadbandtechreport
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12156
      LIVERELOAD_PORT: 35156
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_btr
    ports:
      - "12156:80"
      - "35156:35156"

  cablinginstall:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/cablinginstall
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12157
      LIVERELOAD_PORT: 35157
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_cim
    ports:
      - "12157:80"
      - "35157:35157"

  dentistryiq:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/dentistryiq
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12158
      LIVERELOAD_PORT: 35158
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_diq
    ports:
      - "12158:80"
      - "35158:35158"

  intelligent-aerospace:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/intelligent-aerospace
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12159
      LIVERELOAD_PORT: 35159
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_ias
    ports:
      - "12159:80"
      - "35159:35159"

  industrial-lasers:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/industrial-lasers
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12160
      LIVERELOAD_PORT: 35160
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_ils
    ports:
      - "12160:80"
      - "35160:35160"

  ledsmagazine:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/ledsmagazine
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12161
      LIVERELOAD_PORT: 35161
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilons.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilons.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilons.graphql.base-cms.io}
      TENANT_KEY: ebm_leds
    ports:
      - "12161:80"
      - "35161:35161"

  laserfocusworld:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/laserfocusworld
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12162
      LIVERELOAD_PORT: 35162
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_lfw
    ports:
      - "12162:80"
      - "35162:35162"

  lightwaveonline:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/lightwaveonline
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12163
      LIVERELOAD_PORT: 35163
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_lw
    ports:
      - "12163:80"
      - "35163:35163"

  militaryaerospace:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/militaryaerospace
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12164
      LIVERELOAD_PORT: 35164
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_mae
    ports:
      - "12164:80"
      - "35164:35164"

  offshore-mag:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/offshore-mag
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12165
      LIVERELOAD_PORT: 35165
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_os
    ports:
      - "12165:80"
      - "35165:35165"

  ogj:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/ogj
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12166
      LIVERELOAD_PORT: 35166
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_ogj
    ports:
      - "12166:80"
      - "35166:35166"

  rdhmag:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/rdhmag
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12167
      LIVERELOAD_PORT: 35167
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_rdh
    ports:
      - "12167:80"
      - "35167:35167"

  perioimplantadvisory:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/perioimplantadvisory
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12168
      LIVERELOAD_PORT: 35168
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_pia
    ports:
      - "12168:80"
      - "35168:35168"

  strategies-u:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/strategies-u
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12169
      LIVERELOAD_PORT: 35169
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_su
    ports:
      - "12169:80"
      - "35169:35169"

  vision-systems:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/vision-systems
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12170
      LIVERELOAD_PORT: 35170
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_vsd
    ports:
      - "12170:80"
      - "35170:35170"

  waterworld:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/waterworld
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12171
      LIVERELOAD_PORT: 35171
      SITEMAPS_URI: ${SITEMAPS_URI-https://aerilon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://aerilon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://aerilon.graphql.base-cms.io}
      TENANT_KEY: ebm_ww
    ports:
      - "12171:80"
      - "35171:35171"

  plasticsmachinerymagazine:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/plasticsmachinerymagazine
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12172
      LIVERELOAD_PORT: 35172
      SITEMAPS_URI: ${SITEMAPS_URI-https://picon.sitemaps.base-cms.io}
      RSS_URI: ${RSS_URI-https://picon.rss.base-cms.io}
      GRAPHQL_URI: ${GRAPHQL_URI-https://picon.graphql.base-cms.io}
      TENANT_KEY: ebm_pmm
    ports:
      - "12172:80"
      - "35172:35172"
